#pragma once
enum ComponentType { COMPONENT_SPRITE, 
	COMPONENT_TRANSFORM, 
	COMPONENT_CONTROLLER,
	COMPONENT_UPDOWN,
	COMPONENT_ANIMATION, 
	COMPONENT_BODY, 
	COMPONENT_EXPLOSION,
	COMPONENT_BOMBCOLLIDER,
	COMPONENT_TIMER,
	COMPONENT_AI };