#pragma once

enum GameObjectType { TYPE_MARIO, TYPE_WOOD, TYPE_SIMON, TYPE_BRICK_V,
					TYPE_JACK, TYPE_BEN, TYPE_BOMB,TYPE_FIRE, TYPE_BRICK_H,
					TYPE_BRICK, TYPE_POWERUP_BOMB, TYPE_POWERUP_FIRE, TYPE_POWERUP_SPEED,
					TYPE_CONTROL_UI,TYPE_WIN_UI, TYPE_LOST_UI, TYPE_DOOR, TYPE_UNDEFINED};